export const state = {
  lang: "zh",
  user: null,
  accounts: [],
  groups: [],
  createdInvites: [],
  auditLogs: [],
  workspaces: [],
  workspacesLoaded: false,
  selectedWorkspace: 0,
  selectedSession: 0,
  selectedArtifacts: new Set(),
  selectedUploadFiles: [],
  collapsedFileFolders: new Set(),
  collapsedArtifactFolders: new Set(),
  chatLastEventIds: {},
  sessionPanelWidth: 280,
  filePanelWidth: 300,
  isSessionPanelCollapsed: false,
  isFileExplorerCollapsed: true,
  operationProgress: null,
  workspaceCreateUploadController: null,
};
