export const state = {
  lang: "zh",
  user: null,
  accounts: [],
  groups: [],
  workers: [],
  createdInvites: [],
  auditLogs: [],
  workspaces: [],
  workspacesLoaded: false,
  selectedWorkspace: 0,
  selectedSession: 0,
  selectedArtifacts: new Set(),
  selectedUploadFiles: [],
  collapsedFileFolders: new Set(),
  collapsedArtifactFolders: new Set(),
  chatLastEventIds: {},
  runtimeConfig: {
    chatPollIntervalMs: 2000,
    sseRetryMs: 2000,
    registrationMinPasswordLength: 8,
    batchInviteMaxCount: 100,
    accountMaxSessionsLimit: 10,
    uploadChunkBytes: 8388608,
  },
  sessionPanelWidth: 280,
  filePanelWidth: 300,
  isSessionPanelCollapsed: false,
  isFileExplorerCollapsed: true,
  operationProgress: null,
  workspaceCreateUploadController: null,
};
